
package com.citizeninn.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.4
 * Sat Apr 13 20:01:39 CEST 2013
 * Generated source version: 2.7.4
 */

@XmlRootElement(name = "sayHello", namespace = "http://ws.citizeninn.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sayHello", namespace = "http://ws.citizeninn.com/")

public class SayHello {


}

